Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.PrettyEmbedVideoStreaming:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.PrettyEmbedVideoStreaming: true
